development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: mysore_city_bus_dev
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: mysore_city_bus_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
