# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd50711954f83a4c65d0b126660a758a1966cc34debe983afea4fb17b900c9f8954c4cc9ba731fd11d3fa845bef0eecb0d5eec58fd3b21bc5d4bca1c950404da

test:
  secret_key_base: eca0ee10363b2ea036d977da3ede6680fdb9f2d0fc9473e951f06aade1954e37477ee2f9b4e88119f8cc399bcf4c9f6aac351f30e7d5defc7723f4c5ef94b6df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
